In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
a = [10, 20, 30]
b = [40, 50, 60]

a + b

[10, 20, 30, 40, 50, 60]

In [5]:
x = np.array([10, 20, 30])
y = np.array([40, 50, 60])
type(x)

numpy.ndarray

In [6]:
x + y

array([50, 70, 90])

In [9]:
a * 4

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]

In [ ]:
x * 4

array([ 40,  80, 120])

In [12]:
x

array([10, 20, 30])

In [13]:
x + 1

array([11, 21, 31])

In [14]:
x > 15

array([False,  True,  True])

In [15]:
x

array([10, 20, 30])

In [20]:
x.shape # attribute

(3,)

In [21]:
x.sum() # method

60

In [22]:
x.dtype # data type

dtype('int64')

In [23]:
z = np.array([[1,2,3], [4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
z.shape

(2, 3)

In [25]:
z.dtype

dtype('int64')

In [29]:
z.size

6

In [30]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
z[0]

array([1, 2, 3])

In [32]:
z[0][1]

2

In [34]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [35]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [36]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [37]:
np.linspace(1, 100, 11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [42]:
np.random.randint(1, 100)

19

In [43]:
np.random.randint(1, 100, 10)

array([55, 54, 11, 26, 34, 61,  3, 51, 66, 31])

In [49]:
np.random.seed(42)
mat = np.random.randint(1, 100, (4, 3))
mat

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [50]:
mat.shape

(4, 3)

In [51]:
mat.sum()

746

In [52]:
mat.sum(axis=0)

array([282, 329, 135])

In [53]:
mat

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [54]:
mat.reshape(2, 6)

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24]])

In [57]:
mat.reshape(6, 2)

array([[52, 93],
       [15, 72],
       [61, 21],
       [83, 87],
       [75, 75],
       [88, 24]])

In [58]:
mat

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [60]:
mat[2][1]

87

In [61]:
mat[:, 1]

array([93, 61, 87, 88])

In [62]:
mat[2, :]

array([83, 87, 75])

In [63]:
mat

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [64]:
mat[:3, :2]

array([[52, 93],
       [72, 61],
       [83, 87]])

In [65]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.ones((4,3)) * 2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [71]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
a.dtype

dtype('float64')